// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RodentMedia.Models;

namespace RodentMedia.Migrations
{
    [DbContext(typeof(RodentMediaContext))]
    [Migration("20220312025629_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("RodentMedia.Models.MediaType", b =>
                {
                    b.Property<int>("MediaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaTypeId");

                    b.ToTable("MediaTypes");

                    b.HasData(
                        new
                        {
                            MediaTypeId = 1,
                            MediaTypeName = "Movie"
                        },
                        new
                        {
                            MediaTypeId = 2,
                            MediaTypeName = "Book"
                        },
                        new
                        {
                            MediaTypeId = 3,
                            MediaTypeName = "Television"
                        },
                        new
                        {
                            MediaTypeId = 4,
                            MediaTypeName = "Music"
                        },
                        new
                        {
                            MediaTypeId = 5,
                            MediaTypeName = "Image"
                        },
                        new
                        {
                            MediaTypeId = 6,
                            MediaTypeName = "Theater"
                        },
                        new
                        {
                            MediaTypeId = 7,
                            MediaTypeName = "Printed Publication"
                        },
                        new
                        {
                            MediaTypeId = 8,
                            MediaTypeName = "Other"
                        });
                });

            modelBuilder.Entity("RodentMedia.Models.RatMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("RatMedia");

                    b.HasData(
                        new
                        {
                            MediaId = 1,
                            Description = "Templeton is a rat who helps Charlotte and Wilbur only when offered food. He serves as a somewhat caustic, self-serving comic relief to the plot.",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/916JW20V3yL.jpg",
                            MediaName = "Charlotte's Web",
                            MediaTypeId = 2,
                            RatName = "Templeton",
                            Year = 1952
                        },
                        new
                        {
                            MediaId = 2,
                            Description = "The main protagonist who befriends a worker at a famous Parisian restaurant and assists him in his culinary career.",
                            Image = "https://resizing.flixster.com/gL_JpWcD7sNHNYSwI1ff069Yyug=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzLzc4ZmJhZjZiLTEzNWMtNDIwOC1hYzU1LTgwZjE3ZjQzNTdiNy5qcGc=",
                            MediaName = "Ratatouille",
                            MediaTypeId = 1,
                            RatName = "Remy",
                            Year = 2007
                        },
                        new
                        {
                            MediaId = 3,
                            Description = "During the night, the Rat King and his army fight against the Nutcracker and his fellow toy soldiers.",
                            Image = "https://images-na.ssl-images-amazon.com/images/I/81TxVwDLFnL.jpg",
                            MediaName = "The Nutcracker",
                            MediaTypeId = 6,
                            RatName = "The Rat King",
                            Year = 1892
                        });
                });

            modelBuilder.Entity("RodentMedia.Models.RatMedia", b =>
                {
                    b.HasOne("RodentMedia.Models.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
